# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f86fb91a43074d676224dc969ecfb95c881d657eadf8f4a67ce009d01b0e8a9f5d7358863e1356fd4cdb620c736ba81e8476f61f4a4563fe0293ca3c946cd254

test:
  secret_key_base: 32c9173af37687da4f8d6a0c7e904dbbc830225f291d12b12b1345d7bbee83bc34c0c16ab64787c4caf9464aa353d9ba25ccc097a551eb9cb3724320b03d9a08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
